spring:
  application:
    name: catalogue
    datasource:
    url: jdbc:mysql://ingenius-micro-db.cltqou3p506p.us-east-1.rds.amazonaws.com:3360/ms-catalogue
    username: dev_ext
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
    port: 8082