spring:
  application:
    name: ms-books
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:mysql://ingenius-micro-db.cltqou3p506p.us-east-1.rds.amazonaws.com:3360/ms_ps_books
    username: dev_ext
    password: 3fRXg5lG3kUJt9RO
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8088/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: ${HOSTNAME:localhost}

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: ms-books API
        url: /v3/api-docs
